version: 0.2

phases:
  build:
    commands:
      - echo Packaging CloudFormation Template
      - aws cloudformation package --template-file template.yml --s3-bucket iaac-s3 --output-template-file outputtemplate.yml
  post_build:
    commands:
      - echo Deploying CloudFormation Stack
      - aws cloudformation deploy --template-file outputtemplate.yml --stack-name IaaC-1-stack --capabilities CAPABILITY_IAM